# Generated by Django 3.2.7 on 2021-09-08 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrating',
            name='car_id',
        ),
        migrations.AddField(
            model_name='carrating',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='task_api.car'),
            preserve_default=False,
        ),
    ]
