# Generated by Django 3.2.7 on 2021-09-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_api', '0002_auto_20210908_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrating',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
