version: "3.9"

services:
  db:
    image: postgres
    env_file: .env-db
    ports:
      - "8001:5432"
  web:
    container_name: web
    build:
      context: ./
    volumes:
      - .:/Netguru-recruitment-task/
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db

