version: "3.9"

services:
  db:
    image: postgres
    # volumes:
    #   - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=netguru_api_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Admin123
    ports:
      - "8001:5432"
  web:
    container_name: web
    build:
      context: ./
    # command: gunicorn --env DJANGO_SETTINGS_MODULE=Netguru_api.settings Netguru_api.wsgi
    # command: python manage.py runserver
    volumes:
      - .:/Netguru-recruitment-task/
    ports:
      - "8000:8000"
    depends_on:
      - db

